spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dororo?serverTimezone=UTC
    data-username: root
    data-password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8093
mybatis:
  type-aliases-package: com.data
  mapper-locations: /mapper/*.xml